import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { FadedCard } from "~/components/faded-card";
import { Layout } from "~/components/layout/layout";
import { Navbar } from "~/components/navbar";
import { api } from "~/utils/api";

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>BoostersInn</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-[#1A1A1D] py-18">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-6 ">
          <h1 className="text-4xl font-extrabold tracking-tight text-white text-center">
            Boost Your Way to <span className="text-[#FFF8A3]">Gaming Greatness</span>
          </h1>
          <p className="text-white text-center">
            looking to climb the ranks in your favorite competitive game or unlock exclusive rewards, our team of professional gamers is here to help you achieve your goals.
          </p>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3 md:gap-8 ">
            <FadedCard>
              <h3 className="text-2xl font-bold">Find a booster</h3>
              <div className="text-lg">
                Get boosted - Top quality boosters in any game!
              </div>
            </FadedCard>
            <FadedCard>
              <h3 className="text-2xl font-bold">Prices and Packages</h3>
              <div className="text-lg">
                Checkout our boosting offers and packages!
              </div>
            </FadedCard>
            <FadedCard>
              <h3 className="text-2xl font-bold">Become a Booster</h3>
              <div className="text-lg">
                We are in a constant search for skilled and professional players to fulfill our roster.
              </div>
            </FadedCard>
          </div>
          <div className="bg-black opacity-60">
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
